# Generated by Django 5.0.12 on 2025-05-17 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryBanIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP адрес')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Неудачные попытки')),
                ('time_unblock', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время разблокировки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус блокировки')),
            ],
        ),
    ]
